// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using CoreGraphics;
using Foundation;
using GroupExperiment.Modules;
using GroupExperiment.Modules.Models;
using GroupExperiment.Modules.Utils;
using UIKit;

namespace GroupExperiment
{
	public partial class SummaryController : UIViewController
	{
        public string groupName;
        public string numOfRecipients;
        public double totalAmount;

        string correctPinLength;

        HttpClient client;

        public List<RecipientDTO> recipientDTOList = new List<RecipientDTO>();


        public SummaryController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            Title = "Summary";

            NSNotificationCenter.DefaultCenter.AddObserver(UIKeyboard.WillShowNotification, KeyboardWillMove);
            NSNotificationCenter.DefaultCenter.AddObserver(UIKeyboard.WillHideNotification, KeyboardWillMove);

            MyUtils.ResignResponders(View);

            MyUtils.AddShadow(groupSummaryCard);
            MyUtils.AddShadow(senderSummaryCard);
            MyUtils.AddTextFieldShadow(enterPinView);
            MyUtils.AddTextFieldShadow(remarkTextField);
            MyUtils.AddTextFieldShadow(pinTextField);

            groupSummaryCard.Layer.CornerRadius = 8;
            senderSummaryCard.Layer.CornerRadius = 8;
            enterPinView.Layer.CornerRadius = 8;
            //senderSummaryCard.ClipsToBounds = true;

            //groupNameLabel.Text = groupName;
            recipientsNumberLabel.Text = numOfRecipients;
            totalAmountLabel.Text = "₦" + totalAmount.ToString("N0");

            accBalanceLabel.Text = "₦" + Commonclass.ActiveAccount.AccountBalance.ToString("N0");
            accNumberLabel.Text = Commonclass.ActiveAccount.AccountNumber;
            accTypeLabel.Text = Commonclass.ActiveAccount.AccountType;

            confirmBtn.TouchUpInside += ConfirmBtn_TouchUpInside;

            okayBtn.TouchUpInside += OkayBtn_TouchUpInside;

            cancelPinBtn.TouchUpInside += CancelPinBtn_TouchUpInside;

            pinTextField.EditingChanged += PinTextField_EditingChanged;
        }

        public void KeyboardWillMove(NSNotification notification)
        {
            if (notification.Name == UIKeyboard.WillShowNotification)
            {
                var keyboard = UIKeyboard.FrameBeginFromNotification(notification);

                CGRect frame = View.Frame;
                frame.Y = -keyboard.Height/2;
                View.Frame = frame;
            }

            if (notification.Name == UIKeyboard.WillHideNotification)
            {
                CGRect frame = View.Frame;
                frame.Y = 0;
                View.Frame = frame;
            }
        }

        private void PinTextField_EditingChanged(object sender, EventArgs e)
        {
            if (pinTextField.Text.Length == 4)
            {
                correctPinLength = pinTextField.Text;
            }

            if (pinTextField.Text.Length > 4)
            {
                pinTextField.Text = correctPinLength;
            }
        }

        private void CancelPinBtn_TouchUpInside(object sender, EventArgs e)
        {
            HideViews();
        }

        private void OkayBtn_TouchUpInside(object sender, EventArgs e)
        {
            if (string.IsNullOrWhiteSpace(pinTextField.Text) || pinTextField.Text.Length < 4)
            {
                MyUtils.ShowSimpleAlert("Invalid", "Input a valid pin", this);
            }
            else
            {
                MakeTransfer().Wait(200);
            }
        }

        private void ConfirmBtn_TouchUpInside(object sender, EventArgs e)
        {
            enterPinBackgroundView.Hidden = false;
            UIView.Transition(enterPinView, 0.5f, UIViewAnimationOptions.TransitionCrossDissolve, () => { enterPinView.Hidden = false; }, null);

            if (!string.IsNullOrWhiteSpace(remarkTextField.Text))
            {
                foreach(RecipientDTO recipient in recipientDTOList)
                {
                    recipient.Narration = remarkTextField.Text;
                    Console.WriteLine(recipient.ReceiverAccount + " " + recipient.Narration);
                }
            }
        }

        public async Task MakeTransfer()
        {
            activityBackgroundView.Hidden = false;
            indicator.Hidden = false;
            indicator.StartAnimating();

            client = new HttpClient(MyUtils.GetInsecureHandler());

            string url = "https://localhost:5001/Transaction/make_transfer";
            string url2 = "https://xmtapi.azurewebsites.net/Transaction/make_transfer";

            TransferDTO transfer = new TransferDTO(Commonclass.ActiveAccount.AccountNumber,pinTextField.Text, recipientDTOList.ToArray());

            HttpResponseMessage response = await client.PostAsJsonAsync(url2, transfer);
            var responseString = await response.Content.ReadAsStringAsync();

            indicator.StopAnimating();
            activityBackgroundView.Hidden = true;

            if (response.IsSuccessStatusCode)
            {
                Console.WriteLine(responseString);
                Commonclass.ActiveAccount.AccountBalance -= totalAmount;

                HideViews();

                PerformSegue("toStatus", null);
            }
            else
            {
                Console.WriteLine("Transfer failed");
                Console.WriteLine(responseString);

                MyUtils.ShowSimpleAlert("Transaction failed", responseString, this);

                HideViews();
            }

        }

        public void HideViews()
        {
            enterPinBackgroundView.Hidden = true;
            enterPinView.Hidden = true;
            pinTextField.Text = "";
        }
    }




    public class TransferDTO
    {
        public string SenderAccount { get; set; }
        public string AccountPin { get; set; }
        public RecipientDTO[] Transfers { get; set; }

        public TransferDTO(string senderAccount, string accountPin, RecipientDTO[] transfers)
        {
            this.SenderAccount = senderAccount;
            this.AccountPin = accountPin;
            this.Transfers = transfers;
        }
    }
}
