// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using GroupExperiment.Modules.Models;
using GroupExperiment.Modules.TableSources;
using UIKit;

namespace GroupExperiment
{
	public partial class TransactionDetailController : UIViewController
	{
		public Transaction[] transactionDetails;
		public int index;

		public TransactionDetailController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

			transactionDetailTableView.Source = new TransactionDetailTableSource(transactionDetails);
        }
    }
}
