// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GroupExperiment
{
	public partial class CustomDetailCell : UITableViewCell
	{
		public CustomDetailCell()
        {

        }

		public CustomDetailCell (IntPtr handle) : base (handle)
		{
		}

		public void PopulateCell(double amount, string accountNum, string narration, string date, string refId)
        {
			amountLabel.Text = "₦" + amount.ToString("N0");
			accountNumLabel.Text = accountNum;
            if (string.IsNullOrEmpty(narration))
            {
				narrationLabel.Text = "No narration";
            }
            else
            {
				narrationLabel.Text = narration;
			}
			dateLabel.Text = DateTime.Parse(date).ToString("MM/dd/yyyy hh:mm tt");
			refIdLabel.Text = refId;
		}
	}
}
